- Src/Private/Get-AbrFgtForticare.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.Fortigate.ps1
Add Initial Connection (and Disconnect) using PowerFGT
Display FortiCare info (Status, support, Firmware...)
> Add Connection and FortiCare Info

- AsBuiltReport.Fortinet.Fortigate.json
- Src/Private/Get-AbrFgtRoute.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.Fortigate.ps1
Hi @tpcarman, it is good for use of InfoLevel ?
> Add Route (Summary, Monitor, Static, PBR) Chapiter

- AsBuiltReport.Fortinet.Fortigate.json
- Src/Private/Get-AbrFgtUser.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.Fortigate.ps1
> Add User (User, Group, LDAP, RADIUS) Chapter

- Src/Private/Get-AbrFgtSystem.ps1
Enhance display of System Interface (reduce the number of column)
> System interface

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
> Connection: Add Options for custom Port

- AsBuiltReport.Fortinet.FortiGate.json
- AsBuiltReport.Fortinet.FortiGate.psd1
- CHANGELOG.md
- README.md
- Src/Private/Get-AbrFgtFortiCare.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
- Connection: Add Options for custom Port [#16](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/pull/16) - Fixes [#15](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues/15)
- FortiCare: add Try/Catch for Firmware Upgrade Paths [#17](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/pull/17) - Fixes [#14](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues/14)
Bug fixes
Tested against FortiGate demo environment
> v0.1.1release

- AsBuiltReport.Fortinet.FortiGate.json
- AsBuiltReport.Fortinet.FortiGate.psd1
- README.md
- Src/Private/Get-AbrFgtUser.ps1
Add User SAML Table (and detail of all SAML entry)
need new release of https://github.com/FortiPower/PowerFGT (0.7.0)
> Add User SAML Table

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
Add Options to specify the VDOM for report 
Fix #20
> Add VDOM Support Options

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Private/Get-AbrFgtVPNIPsec.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
Add Chapiter for VPN IPsec Phase 1 and Phase 2 (with Summary and detail info) 
Fix #21
> Add VPN IPsec Phase1 / Phase 2 Chapiter 

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Private/Get-AbrFgtFirewall.ps1
- Src/Private/Get-AbrFgtFortiCare.ps1
- Src/Private/Get-AbrFgtRoute.ps1
- Src/Private/Get-AbrFgtSystem.ps1
- Src/Private/Get-AbrFgtUser.ps1
* Add SubInfo Level 2 for LDAP and RADIUS
* Better display of multiple LDAP/RADIUS
* Display User(Local) Type
(need to merge #27 and rebase this change)
> Enhance user chapiter

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Private/Get-AbrFgtFirewall.ps1
- Src/Private/Get-AbrFgtFortiCare.ps1
- Src/Private/Get-AbrFgtRoute.ps1
- Src/Private/Get-AbrFgtSystem.ps1
- Src/Private/Get-AbrFgtUser.ps1
Only use 3 level and not SubLevel
> Fix infolevel : don't use subLevel

- AsBuiltReport.Fortinet.FortiGate.json
- Src/Private/Get-AbrFgtVPNSSL.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
With VPN SSL Settings and Portal
> Add VPN SSL Chapiter

- Src/Private/Get-AbrFgtVPNSSL.ps1
> VPN(SSL): fix ColumnWidths for Portal Summary

- AsBuiltReport.Fortinet.FortiGate.psd1
- CHANGELOG.md
> Release 0.2.1

- Src/Private/Get-AbrFgtFirewall.ps1
- Src/Private/Get-AbrFgtRoute.ps1
- Src/Private/Get-AbrFgtUser.ps1
- Src/Private/Get-AbrFgtVPNIPsec.ps1
- Src/Private/Get-AbrFgtVPNSSL.ps1
With PS5, you need to use @(variable).count...
> Fix display of Summary Chapiter when there is only 1 entry

- AsBuiltReport.Fortinet.FortiGate.psd1
- CHANGELOG.md
> Release 0.2.2

- Src/Private/Get-AbrFgtFirewall.ps1
Adding ref and some stats about usage of object
Need PowerFGT 0.8.0 (for -meta parameter)
Fix #52
> Add Firewall Address/AddressGroup/IP Pool/Virtual reference

- Src/Private/Get-AbrFgtRoute.ps1
don't display Interface Null but blackhole like FortiGate GUI
> Route(monitor): fix when there is Blackhole on Route Monitor

- AsBuiltReport.Fortinet.FortiGate.psd1
- CHANGELOG.md
- Src/Private/Get-AbrFgtSystem.ps1
> Publish 0.2.2

- AsBuiltReport.Fortinet.FortiGate.json
- Src/Private/Get-AbrFgtSDWAN.ps1
- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
> Add SD-WAN Chapiter

- Src/Private/Get-AbrFgtFortiCare.ps1
there is already a check before
Fix #63
> forticare: don't check BranchUpdateVersion

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Private/Get-AbrFgtFirewall.ps1
You can now have multiple Policy Layout on the same times (normal, interface Pair, Sequence Grouping)
> Enhance Policy layout

- Src/Private/Get-AbrFgtFirewall.ps1
with some stats about Policy (number of policy, status, comments...)
> Add Policy Summary

- Src/Private/Get-AbrFgtFortiCare.ps1
with Expiration Date...
Part of #72 (adding FortiGuard Services on FortiCare section)
> FortiCare: Add information about FortiGuard Services

- Src/Private/Get-AbrFgtSystem.ps1
> Add System HA (Configuration and Members) info

- Src/Public/Invoke-AsBuiltReport.Fortinet.FortiGate.ps1
> Invoke: Add Name and Serial of all members on top of report

- AsBuiltReport.Fortinet.FortiGate.psd1
- CHANGELOG.md
> Release 0.4.1

- Src/Private/Get-AbrFgtFirewall.ps1
Add mac(addr), fix iprange and display when unknown type (sdn...)
> Enhance firewall address (unknown & mac)

- Src/Private/Get-AbrFgtFirewall.ps1
Fix typo (SSH => SSL)
and add VPN SSL summary count (From and to VPN SSL interface with enable and NAT...)
> Policy summary: Fix typo and add VPN SSL (from and to)

- Src/Private/Get-AbrFgtSystem.ps1
> System(DHCP): Fix display of Expire Time when use PS5

- Src/Private/Get-AbrFgtFirewall.ps1
Adding 2 new Firewall type value
* Dynamic (filter)
* interface-subnet (subnet)
> Add new firewall Address Type (Dynamic & Interface-subnet)

- Src/Private/Get-AbrFgtSystem.ps1
> Fix support ps5 (system)

- AsBuiltReport.Fortinet.FortiGate.json
- README.md
- Src/Private/Get-AbrFgtRoute.ps1
With BGP Configuration, Neighbor(Group/Range), Network, Redistribute and Status
> Add BGP (router) Chapiter(s)
